# -*- encoding: utf-8 -*-

stopwords = set([u"ấy", u"à", u"ạ", u"dạ", u"bị", u"bởi", u"cả", u"các", u"cái",
                 u"chỉ", u"chiếc", u"cho", u"chứ", u"chưa", u"có_thể", u"cứ", u"của",
                 u"cùng", u"cũng", u"đã", u"đang", u"đây", u"để", u"đến_nỗi", u"đều", u"điều",
                 u"do", u"đó", u"dưới", u"gì", u"khi", u"không", u"là", u"lại", u"lên", u"lúc",
                 u"mà", u"mỗi", u"gtuy", u"một_cách", u"này", u"nên", u"nếu", u"ngay", u"như",
                 u"nhưng", u"những", u"nơi", u"nữa", u"phải", u"qua", u"ra", u"rằng", u"rất",
                 u"rồi", u"sau", u"sẽ", u"so", u"sự", u"tại", u"thì", u"trên", u"trước", u"từ",
                 u"từng", u"và", u"vẫn", u"vào", u"vậy", u"vì", u"việc", u"với", u"vừa", u"trong_khi",
                 u"tuy_nhiên", u"trong_đó", u"trong", u"do_đó", u"vì_vậy", u"dù_rằng", u"để", u"và",
                 u"được", u"rõ_ràng", u"hay_không", u"nào", u"thay_vì", u"chỉ_vì", u"dù_vậy", u"về",
                 u"sau_khi", u"do_đó", u"trước_hết", u"còn", u"sau_đó", u"cũng_như", u"mọi", u"mặc_dù",
                 u"hoặc", u"dù", u"dĩ_nhiên", u"theo", u"đã", u"nên", u"ông", u"bà", u"cô", u"chú",
                 u"thầy", u"anh", u"chị", u"em", u"cháu", u"bạn", u"tôi", u"nó", u"họ", u"mình", u"mày",
                 u"tao", u"hắn", u"thằng", u"thằng_đó", u"thằng_ấy", u"thắng_đấy", u"chàng", u"nàng",
                 u"chúng_mình", u"chúng_tôi", u"chúng_ta", u"hắn_ta", u"anh_ta", u"cô_ta", u"ông_ta",
                 u"bà_ta", u"lão_ta", u"mụ_ta", u"cậu_ta", u"anh_ấy", u"chị_ấy", u"cô_ấy", u"ông_ấy",
                 u"bà_ấy", u"chú_ấy", u"cậu_ấy", u"em_ấy", u"lão_ấy", u"mụ_ấy", u"bao_gồm", u"cho_biết",
                 u"cho_rằng", u"có_lời", u"cụ_thể", u"chỉ_là", u"cần", u"hãy", u"ai", u"đấy", u"chứ",
                 u"chẳng", u"quá", u"hay_sao", u"được", u"thậm_chí", u"có_thể", u"trong_đó",
                 u"trong", u"tuy_nhiên", u"khi_đó", u"thế_nhưng", u"trước_đó", u"hàng_ngày",
                 u"như_vậy", u"bấy_giờ", u"bấy_lâu", u"bấy_lâu_nay", u"lâu_nay", u"vậy_nên",
                 u"đồng_thời", u"trong_lúc", u"đây_là", u"giờ_đây", u"đối_với", u"có_lẽ", u"tại_sao",
                 u"thế_nào", u"cho_hay", u"trước_khi", u"trên_đây", u"ấy_thế", u"bởi_vì", u"vì_thế",
                 u"sao_thế", u"thế_nên", u"từ_đó", u"do_vậy", u"đồng_thời", u"kể_cả", u"cho_là",
                 u"trước_kia", u'tất_nhiên', u'dù_sao', u'bởi', u'vì_thế', u'sắp_tới', u'theo_đó',
                 u'ngoài_ra', u'nhỉ'])